version: "3"
services:
  frontend:
    image: lavender-frontend
    build: ./frontend
    ports: 
      - "80:80"
    networks:
      - mern-app
    depends_on:
      - backend

  backend:
    image: lavender-backend
    build: ./backend
    environment:
      - MONGO_URI=mongodb+srv://root:root@mernapp.i4orevd.mongodb.net/?retryWrites=true&w=majority
      - PORT=4000
    ports: 
      - "4000:4000"
    networks:
      - mern-app

networks:
  mern-app:
